image: go1.2
script:
  - curl -sLO https://github.com/kr/beanstalkd/archive/v1.9.tar.gz
  - tar -xzf v1.9.tar.gz
  - pushd beanstalkd-1.9
  - make -j4 > make.out 2>&1 || (cat make.out && exit 1)
  - ./beanstalkd -l 127.0.0.1 -p 11300 &
  - sleep 1
  - nc -z 127.0.0.1 11300
  - popd
  - make get
  - make test
services:
  - redis
  - mongodb
