language: go
sudo: false
go:
  - 1.4
  - 1.5
  - tip
env:
  - GOARCH=amd64
addons:
  apt:
    packages:
      - rsyslog
matrix:
  allow_failures:
    - go: tip
before_install:
  - sed -E -i 's|git://github.com/([A-Za-z0-9_]+)/tsuru.git|https://github.com/\1/tsuru|g' .git/config
install:
  - make get
before_script:
  - free
  - vmstat
  - ps aux --sort -rss | head -n 10
  - mongostat -n 1
  - rsyslogd &
  - sleep 1
script:
  - make test GOMAXPROCS=1
  - ./check-fmt.sh
  - make deadcode
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: QJe4k18ACRUP4CDo245vBFu1hpVlcR3JPWjT7NL/vAE/Y5KDn5pNXIREPYIx9F/f8lvjF2RrQxjApeUujRh1PPt2Q53JulvaDCfM5a5SYnk5yoqu3ynlfqU4AOTDa6kzoJ3K4M9X8JhMpOtr3+IOPbwV88FjPvwviZN4p0L/0wc=
services:
  - mongodb
  - redis
after_failure:
  # check for OOM; see https://github.com/travis-ci/travis-ci/issues/3075#issuecomment-68629130
  - sudo dmesg
  - free
  - vmstat
  - ps aux --sort -rss | head -n 10
  # mongostat might not work though if mongod was the process that was OOM-killed
  - mongostat -n 1
after_success:
  # So we can see how much memory is used on success, it is probably borderline
  # Here we can get useful output from mongostat since mongod wasn't OOM-killed
  - free
  - vmstat
  - ps aux --sort -rss | head -n 10
  - mongostat -n 1
