language: go
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install bzr mercurial git libyaml-dev cmake -qq
install:
  - pushd /tmp
  - curl -sLO https://github.com/downloads/libgit2/libgit2/libgit2-0.17.0.tar.gz
  - tar -xzf libgit2-0.17.0.tar.gz
  - mkdir -p libgit2-0.17.0/build
  - pushd libgit2-0.17.0/build
  - cmake ..
  - cmake --build .
  - sudo cmake --build . --target install
  - popd
  - popd
  - sudo ldconfig
  - make get-test
before_script:
  - ./check-fmt.sh
  - make get-prod
script:
  - go test -i ./...
  - for package in `go list ./...`; do go test $package -cpu=1,2,4; done
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
services: mongodb
