language: go
before_install:
  - sudo apt-get update -qq > apt-get.out || (cat apt-get.out && exit 1)
  - sudo apt-get install bzr mercurial git libyaml-dev cmake -qq >> apt-get.out || (cat apt-get.out && exit 1)
install:
  - pushd /tmp
  - curl -sLO https://github.com/downloads/kr/beanstalkd/beanstalkd-1.8.tar.gz
  - tar -xzf beanstalkd-1.8.tar.gz
  - pushd beanstalkd-1.8
  - make -j4 > make.out || (cat make.out && exit 1)
  - ./beanstalkd -l 127.0.0.1 -p 11300 &
  - sleep 3
  - nc -z 127.0.0.1 11300
  - popd
  - popd
  - make get-test
before_script:
  - ./check-fmt.sh
  - make get-prod
script:
  - make test
notifications:
  irc:
    channels:
      - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
  email:
    recipients:
      - tsuru@corp.globo.com
    on_success: change
    on_failure: always
services: mongodb
