language: go
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install bzr mercurial git libyaml-dev -qq
install:
  - make get-test
before_script:
  - ./check-fmt.sh
  - make get-prod
script: make test
branches:
  only: master
notifications:
  irc:
    channels:
      - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
services: mongodb
