language: go
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install bzr mercurial git libyaml-dev -qq
install:
  - make hg
  - make git
  - make bzr
  - make get-test
before_script:
  - ./check-fmt.sh
  - make get-prod
  - ssh-keygen -t rsa -f $HOME/.ssh/ida_rsa -N ""
script: make test
branches:
  only: master
notifications:
  irc:
    channels:
      - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
  email: false
