language: go
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install bzr mercurial git libyaml-dev -qq
install: make get
before_script: ./check-fmt.sh
script: make test
branches:
  only: master
notifications:
  irc:
    - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
